IF(NOT CMAKE_BUILD_TYPE)
    SET(CMAKE_BUILD_TYPE "Release"
        CACHE STRING
        "Choose the type of build, options are:
        Debug, Release, RelWithDebInfo, MinSizeRel."
        FORCE)
endif()
IF( WIN32 )
    SET(CMAKE_PREFIX_PATH "C:/Qt/Qt5.6.2/5.6/msvc2015_64/lib/cmake")
    ADD_COMPILE_OPTIONS(/wd4503)
endif(WIN32)
PROJECT(ProjectEuler)
CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
FIND_PACKAGE(Qt5 5.6 REQUIRED COMPONENTS Core)
find_package(CUDA 8 REQUIRED)
message("toolkit dir ${CUDA_TOOLKIT_ROOT_DIR}")
SET(CMAKE_CUDA_STANDARD 11)
ENABLE_LANGUAGE(CUDA)
LIST(APPEND CUDA_NVCC_FLAGS "-arch=sm_60")
LIST(APPEND CUDA_NVCC_FLAGS "--use_fast_math --default-stream per-thread")
set(CMAKE_CXX_STANDARD 14)
INCLUDE_DIRECTORIES(${CUDA_INCLUDE_DIRS})
IF(WIN32)
    ADD_DEFINITIONS(/D_CRT_SECURE_NO_WARNINGS /D_WINSOCK_DEPRECATED_NO_WARNINGS /DWIN32 /D_WIN32)
    #ADD_DEFINITIONS("$<$<CXX_COMPILER_ID:MSVC>:_CRT_SECURE_NO_WARNINGS;_WINSOCK_DEPRECATED_NO_WARNINGS;WIN32;_WIN32>")
ENDIF(WIN32)
ADD_COMPILE_OPTIONS("$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>>:-stdlib=libc++>")
ADD_COMPILE_OPTIONS("$<$<AND:$<CONFIG:DEBUG>,$<CXX_COMPILER_ID:GNU>>:-g -O0 -fno-omit-frame-pointer -rdynamic>")
ADD_SUBDIRECTORY(core)
ADD_SUBDIRECTORY(problem1)
ADD_SUBDIRECTORY(problem2)
ADD_SUBDIRECTORY(problem3)
ADD_SUBDIRECTORY(problem4)
ADD_SUBDIRECTORY(problem5)
ADD_SUBDIRECTORY(problem6)
ADD_SUBDIRECTORY(problem7)
ADD_SUBDIRECTORY(problem8)
ADD_SUBDIRECTORY(problem9)
ADD_SUBDIRECTORY(problem10)
ADD_SUBDIRECTORY(problem11)
ADD_SUBDIRECTORY(problem12)
ADD_SUBDIRECTORY(problem13)
ADD_SUBDIRECTORY(problem14)
ADD_SUBDIRECTORY(problem15)
ADD_SUBDIRECTORY(problem16)
ADD_SUBDIRECTORY(problem17)
ADD_SUBDIRECTORY(problem18)
ADD_SUBDIRECTORY(problem19)
ADD_SUBDIRECTORY(problem20)
ADD_SUBDIRECTORY(problem21)
ADD_SUBDIRECTORY(problem22)
ADD_SUBDIRECTORY(problem23)
ADD_SUBDIRECTORY(problem24)
ADD_SUBDIRECTORY(problem25)
ADD_SUBDIRECTORY(problem26)
ADD_SUBDIRECTORY(problem27)
ADD_SUBDIRECTORY(problem28)
ADD_SUBDIRECTORY(problem29)
ADD_SUBDIRECTORY(problem30)
ADD_SUBDIRECTORY(problem67)
ADD_SUBDIRECTORY(problem499)
