#include <iostream>

#include <QDebug>
#include <QVector>
#include <vector>
#include <string>
#include <set>
#include <bitset>
#include "core/timer.h"
#include "core/primes.h"
#include "core/BigFloat.h"

using namespace std;

int main()
{
    Timer timer;
    auto primes = primes::primes(10000);
    std::set<long long> pSet;
    for(const auto &p : primes) {
        pSet.insert(p);
    }
    long long maxLen=0;
    long long maxA=0;
    long long maxB=0;
    for(long long a=-999; a<1000; ++a) {
        for(long long b=2; b<=1000; ++b) {
            long long len=0;
            long long f = b;
            long long n = 1;
            while(pSet.find(f) != pSet.end()) {
                ++len;
                f = n * n + a * n + b;
                ++n;
            }
            if(maxLen < len) {
                maxLen = len;
                maxA = a;
                maxB = b;
            }
        }
    }
    qDebug() << "longest prime sequence generated by n^2 + " << maxA << "*n + " << maxB << " a*b=: " << maxA * maxB;
    qDebug() << timer.ticks().count() / 1000.0 << "ms";
    return 0;
}
